version: "3"

services:
  app:
    build:
      context: .
    expose:
      - "8005"
    volumes:
      - static_volume:/app/staticfiles
      - ./app:/app
    env_file:
      - ./.env.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8005
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - app
    volumes:
      - static_volume:/app/staticfiles

volumes:
  postgres_data:
  static_volume:
