# Generated by Django 2.1.15 on 2021-04-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210420_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='state',
        ),
        migrations.AddField(
            model_name='device',
            name='stateAlgo',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='stateReal',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=255, null=True),
        ),
    ]
