# Generated by Django 2.1.15 on 2021-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210420_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='cost',
            new_name='costAlgo',
        ),
        migrations.AddField(
            model_name='device',
            name='costReal',
            field=models.FloatField(default=0.0),
        ),
    ]
