# Generated by Django 2.1.15 on 2021-04-20 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210420_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('realpowervalue', models.FloatField(default=0.0)),
                ('algopowervalue', models.FloatField(default=0.0)),
                ('realstatevalue', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=255, null=True)),
                ('algostatevalue', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=255, null=True)),
                ('costreal', models.FloatField(default=0.0)),
                ('costalgo', models.FloatField(default=0.0)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
