# Generated by Django 2.1.15 on 2021-04-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='observerInSitesIds',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='operatorInSitesIds',
            field=models.CharField(default='', max_length=255),
        ),
    ]
