# Generated by Django 2.1.15 on 2021-04-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210425_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='name',
            field=models.CharField(choices=[('Temperature', 'Temperature'), ('Light', 'Light'), ('Motion', 'Motion'), ('Space', 'Space'), ('Humidity', 'Humidity')], max_length=255),
        ),
    ]
