# Generated by Django 2.1.15 on 2021-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210426_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='core.Sensor'),
        ),
    ]
