# Generated by Django 2.1.15 on 2021-04-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210426_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='devices',
            field=models.ManyToManyField(blank=True, to='core.Device'),
        ),
        migrations.AlterField(
            model_name='site',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='core.Sensor'),
        ),
    ]
