# Generated by Django 2.1.15 on 2021-04-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210427_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='timezone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
