# Generated by Django 2.1.15 on 2021-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_site_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='locationX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='locationY',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
